name: Build Tiny11 Core ISO (Official, Cloud)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Download Tiny11 Builder
      run: |
        git clone https://github.com/ntdevlabs/tiny11builder.git

    - name: Download Windows 11 ISO
      shell: powershell
      run: |
        Invoke-WebRequest `
          -Uri "https://software-download.microsoft.com/download/pr/Win11_23H2_English_x64.iso" `
          -OutFile "win11.iso"

    - name: Mount Windows 11 ISO
      shell: powershell
      run: |
        Mount-DiskImage -ImagePath win11.iso

    - name: Run Tiny11 Coremaker
      shell: powershell
      run: |
        cd tiny11builder
        Set-ExecutionPolicy Bypass -Scope Process -Force
        .\tiny11Coremaker.ps1

    - name: Upload Tiny11 Core ISO
      uses: actions/upload-artifact@v4
      with:
        name: tiny11-core-iso
        path: tiny11builder\tiny11.iso
